severityLevel -> severity as OntlogyTerm
ga4gh-beacon/beacon-v2-Models pull request #94
Opened 2022-03-20 07:43 UTC by mbaudis

This removes the separate SeverityLevel definition in favour of a (renamed) `severity` as simple OntologyTerm.

Discussion in https://github.com/ga4gh-beacon/beacon-v2-Models/issues/91

2022-03-21 10:24 UTC, mbaudis commented
@jrambla I personally would slightly favour to only rename the parameter to `severity` and keep the `SeverityLevel` definition since AFAIK it doesn't differ in the generated structure but fine with both...

2022-03-23 09:34 UTC, jrambla requested changes
I also prefer to type Severity for using a common definition in different schemas.
Can you make it like that, please?

2022-03-23 09:51 UTC, mbaudis commented
@jrambla Have a look - like this? Just rename & cleanup, examples.

2022-03-23 20:56 UTC, jrambla approved these changes

2022-03-23 20:58 UTC, merged